/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import com.mysql.jdbc.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali Raza
 */
public class Task extends javax.swing.JFrame {

    /**
     * Creates new form Task
     */
    Connection cn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public Task() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        task_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Des = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        startdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enddate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        E_ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Task Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Task Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 80, 10);
        jPanel1.add(task_name);
        task_name.setBounds(120, 80, 270, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Description");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 120, 100, 20);

        Des.setColumns(20);
        Des.setRows(5);
        jScrollPane1.setViewportView(Des);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 120, 270, 120);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Start Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 264, 100, 20);

        startdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startdateActionPerformed(evt);
            }
        });
        jPanel1.add(startdate);
        startdate.setBounds(120, 260, 270, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Due Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 307, 64, 30);
        jPanel1.add(enddate);
        enddate.setBounds(120, 310, 270, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Employee ID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 380, 90, 17);
        jPanel1.add(E_ID);
        E_ID.setBounds(120, 370, 270, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 500, 130, 30);

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 500, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Idea(41).jpg"))); // NOI18N
        jLabel2.setText("Start Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-650, -70, 1400, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Task=task_name.getText();
        String DE=Des.getText();
        String SD=startdate.getText();
        String ED=enddate.getText();
        String id=E_ID.getText();
        
        if( Task.equalsIgnoreCase("") || DE.equalsIgnoreCase("") || SD.equalsIgnoreCase("") || ED.equalsIgnoreCase("") || id.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "SOME FIELDS ARE EMPTY", "ERROR" , 1);
        }
        else{
            try
        {
           Class.forName("com.mysql.jdbc.Driver").newInstance();
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull","root","");
           Statement st=cn.createStatement();
           
           String str = "INSERT INTO `Task Detail`(`Task Name`, `Description`, `Start Date`, `End Date`, `Employee ID`) VALUES (?,?,?,?,?)";
           pst = cn.prepareStatement(str);
           
           pst.setString(1, Task);
           pst.setString(2, DE);
           pst.setString(3, SD);
           pst.setString(4, ED);
           pst.setString(5, id);
           
           pst.executeUpdate();
           JOptionPane.showMessageDialog(rootPane, "TASK SAVED", "TASK" , 1);
        }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Des;
    private javax.swing.JTextField E_ID;
    private javax.swing.JTextField enddate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField startdate;
    private javax.swing.JTextField task_name;
    // End of variables declaration//GEN-END:variables
}
